### ISSUE TITLE
Formatting Stylesheet

### ISSUE THREAD

**Issue by cyouh95** [avneryoffe/prj-rev-bwfs-dasmoto#3]
Having everything on one row makes it difficult to read. Consider putting each property on a separate line:

```css
a {
  font-family: helvetica; 
  font-weight: bold; 
  color: blue;
}
```

https://github.com/avneryoffe/prj-rev-bwfs-dasmoto/blob/master/arts%20and%20crafts%20store/resources/style.css
