### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [avneryoffe/prj-rev-bwfs-dasmoto#4]
Instead of putting shared properties such as `font-family: Helvetica;` and `font-weight: bold;` for each of the elements, you can just specify those one time for the `body` element. Since all the other elements are children of (nested inside) the `body` element, they will automatically inherit those properties.

```css
body {
  font-family: Helvetica;
  font-weight: bold;
}
```

https://github.com/avneryoffe/prj-rev-bwfs-dasmoto/blob/master/arts%20and%20crafts%20store/resources/style.css
